alias clear='echo "";echo "";echo "";echo "";echo "";echo "";echo "";echo "";echo "";echo "";echo "";echo "";echo "";echo "";/usr/bin/clear'
alias df='df -Thl'
alias cls='/usr/bin/clear'
alias cd..='cd ..'
alias SU='su'
alias tree='/usr/bin/tree  --dirsfirst -aFI "node_modules|.git|.vagrant|.npm"'
alias reset="tput reset"
alias reser="tput reset"
alias RESET="tput reset"
alias ls='ls -hal --group-directories-first'